Running: rez env rfh -- usdrecord --camera /root/camera01/GEO/renderCam_hrc/renderCam_buffer/renderCam_srt/renderCam --renderer "RenderMan XPU - GPU" --purposes render   scenes/ALab/ALab/entry.usda "renderers/RenderMan XPU - GPU/entry.jpg"
Camera: /root/camera01/GEO/renderCam_hrc/renderCam_buffer/renderCam_srt/renderCam
Renderer plugin: HdPrmanXpuGpuLoaderRendererPlugin
Recording time code: EARLIEST
W15006 {WARNING} Failed to obtain a modification time for light texture : rtxplugin:RtxHioImage.so?filename=/home/nico/usd-render-benchmark/scenes/ALab/ALab/fragment/lightrig/lighting/mk020_0281_export/base/texture/dmp_skydome_alab01_std01_render_high_texture/nuke_texture_export.exr&flipped=false.
W03006 {WARNING} Primvar isScraggled is of type integer, but not constant or uniform on curve geometry WeaveOrKnit.
Error: CUDA error encountered - an illegal memory access was encountered, in accel/renderscene.cpp.cu:439.
terminate called without an active exception
39134 ThreadId=0x7f974b208700: 
-- TRACEBACK BEGIN --
Traceback from hython 20.0.751 (Compiled on linux-x86_64-gcc9.3):
stackTrace(UTsignalHandlerArg) <libHoudiniUT.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo_t*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo_t*, void*) <libHoudiniUT.so>
__GI_raise <libc.so.6>
__GI_raise <libc.so.6>
__GI_abort <libc.so.6>
__gnu_cxx::__verbose_terminate_handler() [clone .cold] <libstdc++.so.6>
__cxxabiv1::__terminate(void (*)()) <libstdc++.so.6>
std::terminate() (eh_terminate.cc:57)
UT_ThreadIOPool::~UT_ThreadIOPool() <libHoudiniUT.so>
__run_exit_handlers <libc.so.6>
__GI_exit <libc.so.6>
xpu::RenderSceneT<DeviceCuda>::ClearShadowQueue(xpu::Context const&) const <libxpu.so>
xpu::RenderSceneT<DeviceCuda>::FlushShadowQueue(xpu::Context const&, unsigned int, xpu::OpacityShadeHitFunc&, xpu::TransmissionShadeHitFunc&, xpu::VolumeDensityShadeHitFunc&, unsigned int, bool) const <libxpu.so>
xpuintegrator::PathTracer<DeviceCuda>::Render(xpu::Context const&, xpu::RenderSceneT<DeviceCuda> const&, xpuintegrator::PathTracer<DeviceCuda>::PerThreadWorkingSet&) <X_PxrPathTracer.so>
xpu::RenderSceneT<DeviceCpu>::FlushShadowQueue(xpu::Context const&, unsigned int, xpu::OpacityShadeHitFunc&, xpu::TransmissionShadeHitFunc&, xpu::VolumeDensityShadeHitFunc&, unsigned int, bool) const <libxpu.so>
xpu::RenderSceneT<DeviceCpu>::FlushShadowQueue(xpu::Context const&, unsigned int, xpu::OpacityShadeHitFunc&, xpu::TransmissionShadeHitFunc&, xpu::VolumeDensityShadeHitFunc&, unsigned int, bool) const <libxpu.so>
start_thread <libpthread.so.0>
__clone <libc.so.6>
-- TRACEBACK END --
39134:  (sent by pid 39134)
-- TRACEBACK BEGIN --
Traceback from hython 20.0.751 (Compiled on linux-x86_64-gcc9.3):
stackTrace(UTsignalHandlerArg) <libHoudiniUT.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo_t*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo_t*, void*) <libHoudiniUT.so>
__nanosleep_nocancel <libpthread.so.0>
__nanosleep_nocancel <libpthread.so.0>
pxrInternal_v0_23__pxrReserved__::UsdAppUtilsFrameRecorder::Record(pxrInternal_v0_23__pxrReserved__::TfWeakPtr<pxrInternal_v0_23__pxrReserved__::UsdStage> const&, pxrInternal_v0_23__pxrReserved__::UsdGeomCamera const&, pxrInternal_v0_23__pxrReserved__::UsdTimeCode, std::string const&) <libpxr_usdAppUtils.so>
wrapFrameRecorder() <_usdAppUtils.so>
hboost::python::objects::function::call(_object*, _object*) const <libhboost_python39-mt-x64.so.1.72.0>
hboost::detail::function::void_function_ref_invoker0<hboost::python::objects::(anonymous namespace)::bind_return, void>::invoke(hboost::detail::function::function_buffer&) <libhboost_python39-mt-x64.so.1.72.0>
hboost::python::detail::exception_handler::operator()(hboost::function0<void> const&) const <libhboost_python39-mt-x64.so.1.72.0>
Translate(pxrInternal_v0_23__pxrReserved__::TfBaseException const&) <_tf.so>
hboost::python::handle_exception_impl(hboost::function0<void>) <libhboost_python39-mt-x64.so.1.72.0>
function_call <libhboost_python39-mt-x64.so.1.72.0>
_PyObject_Call (call.c:281)
pxrInternal_v0_23__pxrReserved__::Tf_PyInitWrapModule(void (*)(), char const*, char const*, char const*, char const*) <libpxr_tf.so>
hboost::python::objects::function::call(_object*, _object*) const <libhboost_python39-mt-x64.so.1.72.0>
hboost::detail::function::void_function_ref_invoker0<hboost::python::objects::(anonymous namespace)::bind_return, void>::invoke(hboost::detail::function::function_buffer&) <libhboost_python39-mt-x64.so.1.72.0>
hboost::python::detail::exception_handler::operator()(hboost::function0<void> const&) const <libhboost_python39-mt-x64.so.1.72.0>
Translate(pxrInternal_v0_23__pxrReserved__::TfBaseException const&) <_tf.so>
hboost::python::handle_exception_impl(hboost::function0<void>) <libhboost_python39-mt-x64.so.1.72.0>
function_call <libhboost_python39-mt-x64.so.1.72.0>
_PyObject_MakeTpCall <libpython3.9.so.1.0>
method_vectorcall <libpython3.9.so.1.0>
_PyEval_EvalFrameDefault <libpython3.9.so.1.0>
_PyFunction_Vectorcall.localalias <libpython3.9.so.1.0>
_PyEval_EvalFrameDefault <libpython3.9.so.1.0>
_PyEval_EvalCode <libpython3.9.so.1.0>
_PyEval_EvalCodeWithName (ceval.c:4361)
PyEval_EvalCodeEx <libpython3.9.so.1.0>
PyEval_EvalCode (ceval.c:828)
run_eval_code_obj <libpython3.9.so.1.0>
run_mod <libpython3.9.so.1.0>
pyrun_file (pythonrun.c:1140)
PyRun_SimpleFileExFlags (pythonrun.c:450)
Py_RunMain <libpython3.9.so.1.0>
_init <hython-bin>
_init <hython-bin>
__libc_start_main <libc.so.6>
_init <hython-bin>
-- TRACEBACK END --
Time: 3:12.26
Memory: 20106728 KB
ERROR: usdrecord returned non-zero exit status
